# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resume_proto/resume.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'resume_proto/resume.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19resume_proto/resume.proto\x12\x06resume\"\x1d\n\rResumeRequest\x12\x0c\n\x04\x66ile\x18\x01 \x01(\x0c\"<\n\x0eResumeResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\r\n\x05phone\x18\x03 \x01(\t2M\n\rResumeService\x12<\n\x0bParseResume\x12\x15.resume.ResumeRequest\x1a\x16.resume.ResumeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'resume_proto.resume_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESUMEREQUEST']._serialized_start=37
  _globals['_RESUMEREQUEST']._serialized_end=66
  _globals['_RESUMERESPONSE']._serialized_start=68
  _globals['_RESUMERESPONSE']._serialized_end=128
  _globals['_RESUMESERVICE']._serialized_start=130
  _globals['_RESUMESERVICE']._serialized_end=207
# @@protoc_insertion_point(module_scope)
